language: node_js
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
node_js:
  - "node"
branches:
  only:
    - master
    - develop
cache:
  yarn: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
script:
  - yarn run setup
  - yarn run lint
  - yarn run flow
  - yarn run test
  - yarn run integration
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
